//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationServicePerson.ServiceReferenceDataBaseProvaider {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDataBaseProvaider.IDataBaseProvaider")]
    public interface IDataBaseProvaider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBaseProvaider/FindNameByChar", ReplyAction="http://tempuri.org/IDataBaseProvaider/FindNameByCharResponse")]
        System.Data.DataSet FindNameByChar(char simbol, int request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBaseProvaider/FindNameByChar", ReplyAction="http://tempuri.org/IDataBaseProvaider/FindNameByCharResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FindNameByCharAsync(char simbol, int request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataBaseProvaiderChannel : WebApplicationServicePerson.ServiceReferenceDataBaseProvaider.IDataBaseProvaider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataBaseProvaiderClient : System.ServiceModel.ClientBase<WebApplicationServicePerson.ServiceReferenceDataBaseProvaider.IDataBaseProvaider>, WebApplicationServicePerson.ServiceReferenceDataBaseProvaider.IDataBaseProvaider {
        
        public DataBaseProvaiderClient() {
        }
        
        public DataBaseProvaiderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataBaseProvaiderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseProvaiderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseProvaiderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FindNameByChar(char simbol, int request) {
            return base.Channel.FindNameByChar(simbol, request);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FindNameByCharAsync(char simbol, int request) {
            return base.Channel.FindNameByCharAsync(simbol, request);
        }
    }
}
