//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationServicePerson {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplicationServicePerson.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот пользователь уже нанят.
        /// </summary>
        internal static string AlreadyHired {
            get {
                return ResourceManager.GetString("AlreadyHired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string any {
            get {
                return ResourceManager.GetString("any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ровно 1 символ.
        /// </summary>
        internal static string clarifyingMessage {
            get {
                return ResourceManager.GetString("clarifyingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет подходящих имен.
        /// </summary>
        internal static string emptuNamesListMessage {
            get {
                return ResourceManager.GetString("emptuNamesListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле ввода пустое.
        /// </summary>
        internal static string emptuRow {
            get {
                return ResourceManager.GetString("emptuRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец программы.
        /// </summary>
        internal static string endAppLog {
            get {
                return ResourceManager.GetString("endAppLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы неправильно ввели имя пользователя или пароль!.
        /// </summary>
        internal static string ErrorAutification {
            get {
                return ResourceManager.GetString("ErrorAutification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введено неправильное количество символов.
        /// </summary>
        internal static string errorCountCharMessage {
            get {
                return ResourceManager.GetString("errorCountCharMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создали список имен.
        /// </summary>
        internal static string FindNamesResultLog {
            get {
                return ResourceManager.GetString("FindNamesResultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите команду: &apos;FIRST&apos; для поиска имен начинающихся с указанной буквы &apos;ANY&apos; для нахождения количества вхождений указанной буквы в именах содержащих ее но не начинающихся с нее.
        /// </summary>
        internal static string helpMessage {
            get {
                return ResourceManager.GetString("helpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввели не правильную команду.
        /// </summary>
        internal static string incorrectRequestMessage {
            get {
                return ResourceManager.GetString("incorrectRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели:  .
        /// </summary>
        internal static string inputMessage {
            get {
                return ResourceManager.GetString("inputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество и список имен начинающиеся на  .
        /// </summary>
        internal static string NumberAndListNames {
            get {
                return ResourceManager.GetString("NumberAndListNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество имен:  .
        /// </summary>
        internal static string NumberNamesMessage {
            get {
                return ResourceManager.GetString("NumberNamesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посчитали количество вхождений в листе.
        /// </summary>
        internal static string numberOccurrencesResultLog {
            get {
                return ResourceManager.GetString("numberOccurrencesResultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация устарела введите новое значение.
        /// </summary>
        internal static string outdatedInformation {
            get {
                return ResourceManager.GetString("outdatedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вывели имена в отобраном листе.
        /// </summary>
        internal static string outNameLog {
            get {
                return ResourceManager.GetString("outNameLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать.
        /// </summary>
        internal static string PasswordMustMatchMessage {
            get {
                return ResourceManager.GetString("PasswordMustMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно зарегистрирован.
        /// </summary>
        internal static string RegistrationCompleteMessage {
            get {
                return ResourceManager.GetString("RegistrationCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество вхождений указанного символа в именах не начинающихся с него,  но его содержащих:  .
        /// </summary>
        internal static string resultMessageButtonAny {
            get {
                return ResourceManager.GetString("resultMessageButtonAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернулись в окно ввода команды.
        /// </summary>
        internal static string returnBackLog {
            get {
                return ResourceManager.GetString("returnBackLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен 1 символ.
        /// </summary>
        internal static string rightInputLog {
            get {
                return ResourceManager.GetString("rightInputLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрали команду.
        /// </summary>
        internal static string selectLog {
            get {
                return ResourceManager.GetString("selectLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск программы.
        /// </summary>
        internal static string startLog {
            get {
                return ResourceManager.GetString("startLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой логин уже занят, пожалуста используйте другой.
        /// </summary>
        internal static string UsernameIsBusyMessage {
            get {
                return ResourceManager.GetString("UsernameIsBusyMessage", resourceCulture);
            }
        }
    }
}
